### ISSUE TITLE
Container query concept

### ISSUE THREAD

**Issue by Einanas** [Einanas/I-Love-Web-LG-DG#1]
```css
 :global(:has(.collapsing-columns)) {
    container-type: inline-size;
  }
```
Here is the [link to the rest](https://github.com/fdnd/components/blob/b423aa5e59d7ce201b2c510e1eb0830720d0f33f/src/lib/templates/CollapsingColumns.svelte#L6-L8) if not clear
